export const groceryCategories = [
  "Fresh Produce",
  "Pantry Staples",
  "Dairy & Eggs",
  "Bakery",
  "Ready-to-Cook",
  "Beverages",
];

export const groceryItems = [
  {
    id: "g1",
    name: "Organic Tomatoes",
    category: "Fresh Produce",
    price: 120,
    unit: "500g",
    description: "Vine-ripened, sweet and firm.",
    imageId: "",
    rating: 4.6,
    tags: ["Fresh", "Local"],
  },
  {
    id: "g2",
    name: "Baby Spinach",
    category: "Fresh Produce",
    price: 95,
    unit: "250g",
    description: "Washed and ready to eat.",
    imageId: "",
    rating: 4.4,
    tags: ["Leafy", "Iron-rich"],
  },
  {
    id: "g3",
    name: "Basmati Rice",
    category: "Pantry Staples",
    price: 280,
    unit: "1kg",
    description: "Long grain, aromatic.",
    imageId: "",
    rating: 4.5,
    tags: ["Pantry"],
  },
  {
    id: "g4",
    name: "Cold-Pressed Olive Oil",
    category: "Pantry Staples",
    price: 650,
    unit: "1L",
    description: "Extra virgin, robust flavor.",
    imageId: "",
    rating: 4.7,
    tags: ["Premium"],
  },
  {
    id: "g5",
    name: "Free-range Eggs",
    category: "Dairy & Eggs",
    price: 90,
    unit: "6 pcs",
    description: "Farm fresh, high protein.",
    imageId: "",
    rating: 4.3,
    tags: ["Protein"],
  },
  {
    id: "g6",
    name: "Greek Yogurt",
    category: "Dairy & Eggs",
    price: 140,
    unit: "400g",
    description: "Creamy and thick.",
    imageId: "",
    rating: 4.2,
    tags: ["Probiotic"],
  },
  {
    id: "g7",
    name: "Sourdough Loaf",
    category: "Bakery",
    price: 180,
    unit: "1 loaf",
    description: "Slow fermented, crusty.",
    imageId: "",
    rating: 4.6,
    tags: ["Artisan"],
  },
  {
    id: "g8",
    name: "Multigrain Bread",
    category: "Bakery",
    price: 95,
    unit: "1 loaf",
    description: "High fiber, soft texture.",
    imageId: "",
    rating: 4.1,
    tags: ["Healthy"],
  },
  {
    id: "g9",
    name: "Chicken Tikka Kit",
    category: "Ready-to-Cook",
    price: 320,
    unit: "450g",
    description: "Pre-marinated, ready in 20 mins.",
    imageId: "",
    rating: 4.4,
    tags: ["Quick"],
  },
  {
    id: "g10",
    name: "Veg Stir-Fry Kit",
    category: "Ready-to-Cook",
    price: 240,
    unit: "350g",
    description: "Fresh veggies with sauce pack.",
    imageId: "",
    rating: 4.3,
    tags: ["Vegan"],
  },
  {
    id: "g11",
    name: "Cold Brew Coffee",
    category: "Beverages",
    price: 160,
    unit: "330ml",
    description: "Smooth, low acidity.",
    imageId: "",
    rating: 4.5,
    tags: ["Caffeine"],
  },
  {
    id: "g12",
    name: "Sparkling Water",
    category: "Beverages",
    price: 90,
    unit: "750ml",
    description: "Mineral water, lightly sparkling.",
    imageId: "",
    rating: 4.0,
    tags: ["Hydration"],
  },
];
